### ISSUE TITLE
Mouse sensitivity slider may be broken? 

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/Open-Sewer-Issues#279]
apteroustänään klo 05.59
mouse sensitivity slider has something wrong with it. its either really fast or really slow no matter where i set it. and the fast/slow part is random.

**Comment by Oskutin** [comment]
#254 linked/same?

**Comment by Oskutin** [comment]
> 
> The slider in the in game options only takes effect after restart. It would be practical if it could be adjusted live, so that you could tweak it easier.
> --

**Comment by Zuntti** [comment]
Fixed.

**Comment by N-G-Neer** [comment]
Still having issues. When launching the game, the slider says 10, but it's actually 0 or 1. When you move it back to 10 and save your settings, then the mouse sensitivity is correct. Have to do this every time the game is launched.

**Comment by Oskutin** [comment]
Are you in Untested branch?

**Comment by N-G-Neer** [comment]
> 
> 
> Are you in Untested branch?

Yes.

**Comment by N-G-Neer** [comment]
This is what happens every time I launch the game.

![20190101175322_1](https://user-images.githubusercontent.com/15633807/50574718-4c993f80-0dee-11e9-8f26-b6e1745707e2.jpg)
![20190101175326_1](https://user-images.githubusercontent.com/15633807/50574719-4c993f80-0dee-11e9-9d87-4d70da19c4c6.jpg)
