### ISSUE TITLE
you send me 2 e-mails telling me it was fixed, but is is NOT please help

### ISSUE THREAD

**Issue by G-maniac** [loiste-interactive/Open-Sewer-Issues#348]
you send me 2 e-mails telling me it was fixed, but is is NOT please help 
HOW can i DELETE the savegames? so i can maybe get rid of corupt old game data?
i tried deleting the game twice now, and re-installing the game again, but the save games remain in the stupid game.... and even wen i started a NEW game, still it steals ALL the inventory from my storage in my appartment after i save and quit, and re-load the game... you say it is fixed but IT IS NOT.. and i wasted 2 days trying to fix this.... even with this save game editor it takes hours to check out if the "workshop" inventory saves what in it... but last time it even deletes everything in the livingroom chest... pleasy please please help me... HOW DO I UPDATE THE GAME SO IT WORKS AGAIN!!

**Comment by Epok13** [comment]
"Fixed apartment furniture storage data not loading (issue #338)" in mentioned in"upcoming changes" in [CHANGES.MD](https://github.com/loiste-interactive/Open-Sewer-Issues/blob/master/CHANGES.md) It means it's fixed, but not yet part of the public version. Be patient.

**Comment by G-maniac** [comment]
okay, Thank You for explaining. i thought that new update broke the old save-games... and my game was still broken... now i read this current version is just broken.. oh, and one more thing.. that homeless guy who askes for a beer or smoke... if im right you can only offer him a room 1x... all times after you offer a room, wich i couldnt give him at the moment for some reason, he just says oohmmmm ahhhh or something, and no interaction possible. second. that homeless guy at the start.. who want his turnip moon... i fed him like a dozen turnip moonshine and nothing. i assume you are fixing all this, and they will actually move into theyr rented appartments by the next update, and offering new/more potentional "renters" ... i dont want to be negative, but seems this update was brought out a little too soon.. i can expect these 'glitches" in a beta game... but i seriously did not expect this in a "official" release update. Thank you and have a wonderfull day

**Comment by Oskutin** [comment]
Things were more broken in the previous update.

**Comment by deseven** [comment]
for now you can just use save editor to restore stuff you lost
